// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPVvrLedwXTd1OTqhAS330_WqRABgjXSw',
    appId: '1:456552526786:web:28f183ea70d416a2b3dc5b',
    messagingSenderId: '456552526786',
    projectId: 'weather-189a3',
    authDomain: 'weather-189a3.firebaseapp.com',
    storageBucket: 'weather-189a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxtJ8pbpW5QAanUTdwatY4WRYTYEGy4ks',
    appId: '1:456552526786:android:944f98253b19e273b3dc5b',
    messagingSenderId: '456552526786',
    projectId: 'weather-189a3',
    storageBucket: 'weather-189a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYVJpJG3KE-zbWQw3PvAqYy-yP1ZWBWwY',
    appId: '1:456552526786:ios:de3e0059c188fcabb3dc5b',
    messagingSenderId: '456552526786',
    projectId: 'weather-189a3',
    storageBucket: 'weather-189a3.appspot.com',
    iosBundleId: 'com.example.weatherReport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYVJpJG3KE-zbWQw3PvAqYy-yP1ZWBWwY',
    appId: '1:456552526786:ios:de3e0059c188fcabb3dc5b',
    messagingSenderId: '456552526786',
    projectId: 'weather-189a3',
    storageBucket: 'weather-189a3.appspot.com',
    iosBundleId: 'com.example.weatherReport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPVvrLedwXTd1OTqhAS330_WqRABgjXSw',
    appId: '1:456552526786:web:681b62070803bf06b3dc5b',
    messagingSenderId: '456552526786',
    projectId: 'weather-189a3',
    authDomain: 'weather-189a3.firebaseapp.com',
    storageBucket: 'weather-189a3.appspot.com',
  );
}
